 
/******************************************************************************/
/* CREATE OBJECT
*******************************************************************************/
create or replace view FACT_VEN_NEW_PRODUCT_ROLLOUT_COVERAGE(
	NEW_PRODUCT_ROLLOUT_COVERAGE_KEY,
	NEW_PRODUCT_ROLLOUT_COVERAGE_BK,
	VM_KEY,
	NEW_PRODUCT_ROLLOUT_COVERAGE_VM_MONTH_DATE,
	VM_BK,
	PRODUCT_KEY,
	PRODUCT_BK,
	PRODUCT_MAIN_CATEGORY_CODE_KEY,
	PRODUCT_MAIN_CATEGORY_CODE,
	SUB_CHANNEL_CODE_KEY,
	SUB_CHANNEL_CODE,
	CSP_CODE_KEY,
	CSP_CODE,
	VM_PRODUCT_COUNT
) as
WITH PRODUCT_STATUS AS (
    SELECT DISTINCT 
        VP.PRODUCT_KEY,
        VP.PRODUCT_BK,
        PHS.PRODUCT_CODE,
        PHS.PRODUCT_NAME_JP,
        PHS.MAIN_CATEGORY,
        PHS.PRODUCT_STATUS_CODE,
        PHS.BUSINESS_START_DATE,
        PHS.BUSINESS_END_DATE
    FROM VEN_PRODUCT_HISTORY_STATUS PHS
    JOIN VEN_PRODUCT VP
        ON PHS.PRODUCT_CODE = VP.PRODUCT_CODE
    WHERE 
        PHS.PRODUCT_STATUS_CODE = 'NEWPRODUCT'
        AND PHS.PRODUCT_CODE IS NOT NULL
        AND PHS.PRODUCT_CODE NOT IN ('', '?')
),
VM_INVENTORY AS (
    SELECT 
        VIM.PRODUCT_CODE,
        VIM.INVENTORY_MONTH_END_DATE,
        VM.VM_KEY,
        VM.VM_BK,
        VM.OPERATION_UNIT_KEY,
        VM.OPERATION_UNIT_CODE,
        VM.SUB_CHANNEL_CODE_KEY,
        VM.SUB_CHANNEL_CODE,
        VM.CSP_CODE_KEY,
        VM.CSP_CODE
    FROM VEN_MACHINE_MONTH_END_INVENTORY VIM
    JOIN VEN_VENDING_MACHINE VM
        ON VIM.VM_KEY = VM.VM_KEY
),
INVENTORY_WITH_STATUS AS (
    SELECT 
        VI.VM_KEY,
        VI.VM_BK,
        VI.PRODUCT_CODE,
        VI.INVENTORY_MONTH_END_DATE,
        VI.OPERATION_UNIT_KEY,
        VI.OPERATION_UNIT_CODE,
        VI.SUB_CHANNEL_CODE_KEY,
        VI.SUB_CHANNEL_CODE,
        VI.CSP_CODE_KEY,
        VI.CSP_CODE,
        PS.PRODUCT_KEY,
        PS.PRODUCT_BK,
        PS.PRODUCT_NAME_JP,
        PS.MAIN_CATEGORY
    FROM VM_INVENTORY VI
    JOIN PRODUCT_STATUS PS
        ON VI.PRODUCT_CODE = PS.PRODUCT_CODE
    WHERE VI.INVENTORY_MONTH_END_DATE <= PS.BUSINESS_END_DATE
),
COMPANY_PRODUCT_COVERAGE AS (
    SELECT 
        PRODUCT_KEY,
        PRODUCT_BK,
        PRODUCT_CODE,
        PRODUCT_NAME_JP,
        MAIN_CATEGORY,
        INVENTORY_MONTH_END_DATE,
        COUNT(DISTINCT VM_KEY) AS VMS_WITH_PRODUCT_COMPANY,
        (SELECT COUNT(VM_KEY) FROM VM_INVENTORY) AS COMPANY_LEVEL
    FROM INVENTORY_WITH_STATUS
    GROUP BY 
        PRODUCT_KEY, 
        PRODUCT_BK, 
        PRODUCT_CODE, 
        PRODUCT_NAME_JP, 
        MAIN_CATEGORY, 
        INVENTORY_MONTH_END_DATE
),
GROUPED_PRODUCT_COVERAGE AS (
    SELECT 
        PRODUCT_KEY,
        PRODUCT_BK,
        PRODUCT_CODE,
        PRODUCT_NAME_JP,
        MAIN_CATEGORY,
        VM_KEY,
        VM_BK,
        OPERATION_UNIT_KEY,
        OPERATION_UNIT_CODE,
        SUB_CHANNEL_CODE_KEY,
        SUB_CHANNEL_CODE,
        CSP_CODE_KEY,
        CSP_CODE,
        COUNT(DISTINCT VM_KEY) AS VMS_WITH_PRODUCT_FILTERED
    FROM INVENTORY_WITH_STATUS
    GROUP BY 
        PRODUCT_KEY,
        PRODUCT_BK,
        PRODUCT_CODE,
        VM_KEY,
        VM_BK,
        PRODUCT_NAME_JP,
        MAIN_CATEGORY,
        OPERATION_UNIT_KEY,
        OPERATION_UNIT_CODE,
        SUB_CHANNEL_CODE_KEY,
        SUB_CHANNEL_CODE,
        CSP_CODE_KEY,
        CSP_CODE
)
SELECT
    MD5(
        'VEN' || '^' || 'ROLLOUTCOVERAGE' || '^' || COALESCE(G.VM_KEY, '^') || '^' ||
        COALESCE(C.PRODUCT_CODE, '^') || '^' || COALESCE(C.INVENTORY_MONTH_END_DATE, '^') || '^' ||
        COALESCE(G.MAIN_CATEGORY, '^') || '1' || '^'
    ) AS NEW_PRODUCT_ROLLOUT_COVERAGE_KEY,

    'VEN' || '^' || 'ROLLOUTCOVERAGE' || '^' || COALESCE(G.VM_KEY, '^') || '^' ||
    COALESCE(C.PRODUCT_CODE, '^') || '^' || COALESCE(C.INVENTORY_MONTH_END_DATE, '^') || '^' ||
    COALESCE(G.MAIN_CATEGORY, '^') || '1' || '^' AS NEW_PRODUCT_ROLLOUT_COVERAGE_BK,

    G.VM_KEY AS VM_KEY,
    C.INVENTORY_MONTH_END_DATE AS NEW_PRODUCT_ROLLOUT_COVERAGE_VM_MONTH_DATE,
    G.VM_BK AS VM_BK,
    G.PRODUCT_KEY AS PRODUCT_KEY,
    G.PRODUCT_BK AS PRODUCT_BK,
    MD5('VEN' || '^' || 'MAINCATEGORY' || '^' || COALESCE(G.MAIN_CATEGORY, '^')) AS PRODUCT_MAIN_CATEGORY_CODE_KEY,
    G.MAIN_CATEGORY AS PRODUCT_MAIN_CATEGORY_CODE,

    G.SUB_CHANNEL_CODE_KEY AS SUB_CHANNEL_CODE_KEY,
    G.SUB_CHANNEL_CODE AS SUB_CHANNEL_CODE,
    G.CSP_CODE_KEY AS CSP_CODE_KEY,
    G.CSP_CODE AS CSP_CODE,

    1 AS VM_PRODUCT_COUNT

FROM GROUPED_PRODUCT_COVERAGE G
JOIN COMPANY_PRODUCT_COVERAGE C
    ON G.PRODUCT_CODE = C.PRODUCT_CODE

ORDER BY C.PRODUCT_CODE, C.INVENTORY_MONTH_END_DATE;
